### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by NChongyuan** [quantumbeam/BBO-Rietveld#1]
Hello, I am tring to use your package to do refinement on my data. But I am a beginner in both python and docker. I met many problems during the installation process in Windows system. I am not sure if I do anything wrong. Could you please help me to verify it? Sorry I am also new for this community. So my format of questions maybe wrong as well...

Here is the step I have tried and some problem I met.
1. I installed docker in my system and cloned the repository to my computer under this path: 'E:\BBO-Rietveld-master'
2. Bbo-rietveld docker image has been built on terminal, the command was run in the same directory. The docker image was ceated like this.
    REPOSITORY     TAG       IMAGE ID       CREATED        SIZE
    bbo-rietveld   latest    87f8977cb0e8   5 months ago   3.5GB

Then I did 'run.sh' in the terminal. It shows this window like in the following image for 2 seconds and then it disappear, no error shown, and no container was running. (Git has been installed in order to run 'sh' file.) It is empty in the container list. 
![image](https://user-images.githubusercontent.com/39340614/116828145-2db53e80-ab9d-11eb-8f9d-f06262854ddd.png)

Then I open  http://127.0.0.1:8888/?token={TOKEN} in my browser and it shows the following interface. 
![image](https://user-images.githubusercontent.com/39340614/116828522-8a195d80-ab9f-11eb-8fbf-cbe8de956273.png)

I run 'jupyter notebook list' in the terminal and got a running server link: 'http://localhost:8888/?token=0e998b6fcde8bd58da4910554797344819189bf01c475bc3'
After entering this link, I opened the jupyterlab interface as following. And it shows some error when running cells.
![image](https://user-images.githubusercontent.com/39340614/116828659-5854c680-aba0-11eb-9739-e971021107f2.png)

It looks like I don't have the module 'optuna'. 

3. Then I tried to run the image directly but it does not work.
![image](https://user-images.githubusercontent.com/39340614/116828799-55a6a100-aba1-11eb-9313-2e36c834f21e.png)
![image](https://user-images.githubusercontent.com/39340614/116828811-71aa4280-aba1-11eb-8425-0f2fc529ca4e.png)

4. Then I installed optuna by 'pip install git+https://github.com/optuna/optuna.git@v0.14.0'. But there is the same error in the jupyterlab.
![image](https://user-images.githubusercontent.com/39340614/116828847-b2a25700-aba1-11eb-88b9-a605989ead42.png)

5. At last, I also ran the command that you provided 'docker pull resnant/bbo-rietveld:v1.0' and now is:
REPOSITORY             TAG       IMAGE ID       CREATED        SIZE
bbo-rietveld           latest    87f8977cb0e8   5 months ago   3.5GB
resnant/bbo-rietveld   v1.0      8f6833e9ff59   9 months ago   3.5GB

I tried to refer to the command in 'run.sh'. But I don't know what the pwd means. 
SCRIPT_DIR=$(cd $(dirname $0); pwd)
docker run --rm -v ${SCRIPT_DIR}/:/bbo_rietveld -p 8888:8888 -it resnant/bbo-rietveld:v1.0

What is the right command line I should use? Or is there anything else I should do to setup a proper envirment for your code?

Thank you very much.

**Comment by resnant** [comment]
Hi @NChongyuan,

There seems to be a problem with the execution of run.sh.
We are developing BBO-Rietveld on Ubuntu, so we are not familiar with the Windows terminal environment. 

As you mentioned, please try to run the Docker container manually and check what will happen.
> I tried to refer to the command in 'run.sh'. But I don't know what the pwd means.
SCRIPT_DIR=$(cd $(dirname $0); pwd)
docker run --rm -v ${SCRIPT_DIR}/:/bbo_rietveld -p 8888:8888 -it resnant/bbo-rietveld:v1.0

`pwd` is the Linux command to show the current working directory.
https://en.wikipedia.org/wiki/Pwd
Namely, this command means mounting the current directory to `/bbo_rietveld` in the Docker container.
Please refer here:
https://docs.docker.com/storage/bind-mounts/
https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10

I think this would work:
```
docker run --rm -v ${pwd}:/bbo_rietveld -p 8888:8888 -it resnant/bbo-rietveld:v1.0
```

**Comment by NChongyuan** [comment]
Hello @resnant ,

Firstly, I tried your command directly in the cmd but it does not work and it shows the 'syntax error'.
And I also tried to run this command in the run.sh, however, it still does not work.

So I refer to the question in: 
https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10
and notice that in Window should be 'docker run --rm -it -v %cd%:....'

So I changed the command to:
docker run --rm -it -v %cd%:/bbo_rietveld -p 8888:8888 -it resnant/bbo-rietveld:v1.0
And it shows this state:
![image](https://user-images.githubusercontent.com/39340614/117360538-35d0ef00-aeb9-11eb-8aa2-d7ad493d9d1d.png)
Next I copy this link in my browser.
http://127.0.0.1:8888/?token=8adcae730e02f6492e28645c131917ce0bd8e67e9da69ee6

It works! Now there is a container running.
![image](https://user-images.githubusercontent.com/39340614/117361371-3f0e8b80-aeba-11eb-8fa8-4f70e54831f8.png)

Then I tried to run one of the example Y2O3 inside to test. It seems working well now. 

![image](https://user-images.githubusercontent.com/39340614/117362108-281c6900-aebb-11eb-911b-758ad9a45804.png)

![image](https://user-images.githubusercontent.com/39340614/117362147-336f9480-aebb-11eb-8a46-fd2370a9d3c3.png)
![image](https://user-images.githubusercontent.com/39340614/117362161-38ccdf00-aebb-11eb-8ab4-0c6d514ed679.png)

Then my new questions are: 
1. Is there any tutorial or userguide for your package? I don't find it in the package. I saw there is a file called YOUR_MATERIAL. This seems to be the right one for me. Whether I only need to change the code in cell [2] 'configuration'?

2. I notice that in the data folder (I guess they are the input files), there are several files such as Y2O3.cif, Y2O3.csv, Y2O3.gpx, Y2O3_init.gpx.
As I know, the Y2O3.cif is the crystall structure file for the standard phase. And the Y2O3.csv seems to be the raw data. And the 
other two seems files from GSAS. But should I have all of them to start the refinement? 

3. What can I do if I have a big set of data of around over 200 samples at once? They have similar phase (at least the same crystal structure) but also may exsist some secondary phases.... The most important information I would like to get is the lattice parameter of the main phase in the sample. Is it possible to have it as a table or list?

Thank you very much.

**Comment by resnant** [comment]
I'm glad to hear BBO-Rietveld worked. 😄 

Q1:
> Is there any tutorial or userguide for your package?

We provide three notebooks (Y2O3, DSMO, LiCoO2) for the tutorial.
But we do not have a userguide of BBO-Rietveld.
Because except for the definition of the objective function, most of our code is just calling the Optuna and GSAS APIs. Please refer to the documentation of each software for the usage of those APIs.

https://gsas-ii.readthedocs.io/en/latest/GSASIIscriptable.html#
https://optuna.readthedocs.io/en/v0.19.0/

> Whether I only need to change the code in cell [2] 'configuration'?

In 'YOUR_MATERIAL.ipynb', at least you have to 
- specify your input files in cell [2] and [4]
- define your objective function in cell [5]

Please use other notebooks as a template to write code for their own use.

Q2:
Generally, a crystal structure (.cif) , a diffraction pattern (.csv), and an instrument parameter (.prx) files are required to run Rietveld refinement.
GSAS project file (.gpx) can contain these file and other all settings used for the refinement.
You do not need gpx files if you create a new GSAS project from cif, csv and prx files in your code as we do in the Y2O3 notebook.
If you have to set some constraints on the GSAS project or start with a pre-refined project, you have to specify the gpx file instead of loading cif and other files. Please refer to DSMO and LiCoO2 notebooks.

Q3:
You can loop the BBO-Rietveld run for all your samples. Once the refinements completed, you can easily load the gpx files via GSAS Python APIs and make a table of lattice parameters.
But I think that will be a lot of work, so I recommend that you first run BBO-Rietveld on some of those files to get used to using the software.

As you know, the Rietveld refinement of materials including impurity phases can be very complex. If only the lattice parameters of the main phase are important, I suggest that you first try to analyze them ignoring the impurities.

**Comment by resnant** [comment]
I will close this issue. Please reopen this or open another issue if you need discussion.
